{
        'name': 'Purchase Gainde',
        'summary': "Extensions Gainde pour demandes d'achat, budgets et approbations",
        'description': """
Ce module étend les fonctionnalités standard Odoo autour des modèles :
- purchase.request / purchase.request.line : workflow avancé d'approbation, split budgétaire,
    états supplémentaires, intégration avec approval.route.document et génération de RFQ.
- budget.analytic / budget.line : gestion des budgets analytiques, révisions et vues dédiées.
- user.management : génération de Domain Access par profil (access_users_manager) avec
    bouton de rechargement des domaines par défaut.
- Portail demandes d'achat : vues et comportements personnalisés pour les demandes côté portail.
""",
    'version': '18.0.1.0.1',
    'author': 'Gainde',
    'website': '',
    'category': 'Purchases',
    'license': 'LGPL-3',
    'images': ['static/description/budget_icon.png'],
    'depends': [
        'purchase',
        'gainde_partner_legal',
        'purchase_request',
        'account_followup',
        'partner_tier_account',
        'bf_portal_purchase_request',
        'hr',
        'hr_payroll',
        'portal',
        'mail',
        'account',
        'account_budget',
        'account_asset_from_invoice',
        'hr_expense',
        'xf_approval_route_purchase',
        'xf_approval_route_expense',
        'xf_approval_route_base',
        'access_users_manager',
        'password_security',
        'bc_gainde',
        'amount_to_word',
        'syn_disable_quick_create',
        #'partner_email_check',
        # 'odoo_user_login_security',

    ],
     'data': [
         'data/mail_template_purchase_order.xml',
         'data/approval_route_data.xml',
         'data/approval_route_data_partner_product.xml',
         'data/approval_route_data_purchase.xml',
         'data/approval_route_data_expense.xml',
         'data/disable_purchase_reports.xml',
         'data/menu_labels_override.xml',
         'security/budget_security.xml',
         'security/user_directory_lockdown.xml',
        #  'security/access_users_manager_lockdown.xml',
         'security/base_translation_export_security.xml',
  #  'security/res_users_rule.xml',
         'security/temp_disable_user_lockdown.xml',
          'data/config/user_profiles_config.xml',
          #          'data/config/user_profiles_implied_groups.xml',
      'views/portal_templates.xml',
    'views/portal_menu.xml',
      'views/purchase_request_disable_make_po_view.xml',
        'views/purchase_approval_route.xml', 
        'wizard/purchase_request_line_reject_view.xml',
                'wizard/purchase_request_line_make_purchase_order_view_gainde.xml',
            'wizard/budget_revise_confirm_view.xml',
           'data/analytic_plan_data.xml',
            'views/purchase_request_view.xml',  
            'views/product_view.xml',
            'views/partner_product_approval_views.xml',

        'views/purchase_amount_stage_views.xml',
        'views/purchase_tdr_views.xml',
          'views/analytic_account_views.xml',
          'views/purchase_order_views.xml',
                'views/budget_menus.xml',  
                'views/budget_line_views.xml',
                'views/user_management_views.xml',
                'views/hr_expense_sheet_submitter_view.xml',
                'views/hr_expense_sheet_approve_visibility.xml',
                'views/hr_expense_sheet_hide_approval_route.xml',
                'views/hr_expense_sheet_approval_route_admin_view.xml',
                "security/ir.model.access.csv",
    ],
    'post_init_hook': 'post_init_gainde_company',
    'demo': [
        'data/demo/approval_route.xml',
        'data/config/user_profiles_users_config.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'purchase_gainde/static/src/js/portal.js',
            'purchase_gainde/static/src/xml/xml/purchase_request.xml',
        ],
        'web.assets_backend': [
            'purchase_gainde/static/src/js/modal_expand_button.js',
            'purchase_gainde/static/src/js/safe_access_action_buttons.js',
            # 'purchase_gainde/static/src/js/disable_relational_create_exception.js',
        ],
    },
    'installable': True,
    'application': False,
}
