from . import treasury_payment
from . import treasury_receipt
from . import account_move
from . import account_asset
from . import treasury_forecast
from . import treasury_category
from . import treasury_forecast_wizard
from . import res_config_settings
from . import treasury_invoice_template
from . import treasury_invoice_template_line
from . import treasury_kpi_wizard
from . import treasury_payment_schedule_wizard
from . import treasury_salary_payment_wizard
from . import treasury_payroll_batch
from . import hr_payslip
from . import hr_expense
from . import treasury_payroll_order_wizard
from . import treasury_payroll_disbursement_wizard
from . import treasury_payment_plan_wizard
