from . import purchase_request
from . import approval_route
from . import approval_route_document
from . import portal_purchase_request
from . import purchase_request_line
from . import purchase_request_approval
from . import product_template
from . import user_profile_extension
from . import user_management_extension
from . import access_user_management_patch
from . import res_partner_name_get_patch
from . import res_users
# from . import domain_access_extension
from . import purchase_order
from . import purchase_amount_stage
from . import purchase_tdr
from . import account_analytic_account
from . import field_domain_rule_line
from . import budget_analytic
from . import account_analytic_plan
from . import field_domain_rule
from . import budget_line
from . import partner_product_approval
# Analytique auto (factures/notes de frais) : activable plus tard
from . import analytic_distribution_helper
from . import account_move_line
from . import hr_expense
from . import hr_expense_sheet
from . import ir_attachment
from . import hr_expense_sheet_approval
