from . import project_project
from . import project_task
from . import hr_employee
from . import account_analytic_line
from . import purchase_order_line
from . import planning_slot
from . import project_milestone
from . import purchase_order
from . import purchase_requisition
from . import purchase_request
from . import hr_employee_profile
from . import user_profiles_project_management
