{
  "name": "Treasury Management V3.1",
  "version": "3.1",
  "category": "Accounting",
  "summary": "Treasury end-to-end (V3.1 corrigée)",
  "images": ["static/description/icon.png"],
  "depends": ["web", "account", "account_asset", "mail", "purchase", "hr_payroll", "hr_expense", "account_bank_statement_import", "report_xlsx"],
    "data": [
      "security/security.xml",
      "security/ir.model.access.csv",
      "data/sequence.xml",
      "data/payment_terms.xml",
      "data/sequence_receipt.xml",
      "data/treasury_receipt_sync_action.xml",
      "data/cron.xml",
    "views/treasury_salary_payment_wizard_views.xml",
    "views/treasury_payment_views.xml",
    "views/treasury_receipt_views.xml",
    "views/account_move_views.xml",
    "views/treasury_transaction_views.xml",
    "views/account_asset_views.xml",
    "views/treasury_forecast_views.xml",
    "views/treasury_forecast_wizard_views.xml",
    "views/treasury_category_views.xml",
    "views/treasury_kpi_kanban.xml",
    "views/treasury_kpi_views.xml",
    "views/treasury_invoice_template_views.xml",
    "views/treasury_payment_schedule_wizard_views.xml",
    "views/treasury_payment_plan_wizard_views.xml",
    "views/treasury_cash_views.xml",
    "views/treasury_external_views.xml",
    "views/res_config_settings_views.xml",
    "views/treasury_payroll_batch_views.xml",
    "views/treasury_payroll_order_wizard_views.xml",
    "views/menus.xml",
    "views/treasury_payroll_disbursement_wizard_views.xml",
    "reports/treasury_templates.xml",
    "reports/treasury_kpi_template.xml",
    "reports/treasury_reports.xml"
  ],
  "assets": {
    # Odoo 17/18 : web.assets_web et web.assets_qweb ont été supprimés.
    # Tous les assets (JS, XML templates, SCSS) vont dans web.assets_backend.
    "web.assets_backend": [
      "treasury_management/static/src/scss/treasury_kpi_dashboard_v2.scss",
      "treasury_management/static/src/scss/treasury_payment_dashboard.scss",
      "treasury_management/static/src/js/treasury_kpi_dashboard.js",
      "treasury_management/static/src/xml/treasury_kpi_dashboard.xml",
      "treasury_management/static/src/js/treasury_kpi_dashboard_v2.js",
      "treasury_management/static/src/xml/treasury_kpi_dashboard_v2.xml",
      "treasury_management/static/src/js/treasury_payment_dashboard.js",
      "treasury_management/static/src/xml/treasury_payment_dashboard.xml",
    ],
  },
  "application": True
}
