{
    'name': 'Gainde Legal Contract Management',
    'version': '1.0.0',
    'category': 'Legal',
    'summary': 'Gestion Juridique des Contrats, Avenants, Contentieux',
    'author': 'Issakha Diallo',
    'depends': [
        'base', 'mail', 'documents', 'documents_hr', 'documents_hr_payroll',
        'calendar', 'account', 'hr', 'hr_payroll', 'sale','base_automation',
        'web', 'contacts', 'purchase', 'purchase_gainde',
    ],
    'data': [
        'data/hr_departments_data.xml',
        'data/legal_contract_sequences.xml',
        'data/legal_contract_stages.xml',
        'data/legal_litigation_stages.xml',
        'data/legal_amendment_stages.xml',

        'security/legal_groups.xml',
        'security/legal_contract_security.xml',
        'security/ir.model.access.csv',

        'data/config/user_profiles_config.xml',

        'views/legal_contract_views.xml',
        'views/legal_contract_type_views.xml',
        'views/legal_contract_amendment_views.xml',
        'views/legal_litigation_views.xml',
        'views/documents_views.xml',
        'views/account_move_views.xml',
        'views/hr_payslip_views.xml',
        'views/res_company_views.xml',
        'views/sign_server_actions.xml',
        'views/sign_wizard_views.xml',
        'views/res_users_views.xml',

        'data/automated_actions.xml',
        'data/legal_contract_cron.xml',

        # 'reports/contract_common_blocks.xml',
        # 'reports/contract_specific_templates.xml',
        # 'reports/contract_main_template.xml',
        'reports/common_layout.xml',
        'reports/report_contract_individual.xml',
        'reports/report_contract_employee.xml',
        'reports/report_contract_business.xml',
        'reports/report_contract_market.xml',
        'reports/report_actions.xml',
        'reports/report_contract_cdi.xml',
        'reports/report_contract_prestation.xml',
        'reports/report_contract_nda.xml',
        'reports/report_contract_protocol.xml',
        'reports/report_contract_subscription_orbus_bank.xml',
        'reports/report_contract_subscription_orbus_insurance.xml',

        'data/category_nda_data.xml',
        'data/category_protocol_data.xml',
        'data/category_business_data.xml',
        'data/category_market_data.xml',
        'data/category_individual_data.xml',
        'data/category_subscription_orbus_bank_data.xml',
        'data/category_subscription_orbus_insurance_data.xml',

        'views/legal_contract_menu.xml',
    ],
    'external_dependencies': {
        'python': ['endesive', 'cryptography', 'pymupdf'],
    },
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': '_uninstall_cleanup_ged',
    'images': ['static/description/icon.png'],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
