{
    "name": "Asset Management Gainde",
    "version": "18.0.1.0.0",
    "summary": "Overrides pour asset_management",
    "category": "Assets",
    "author": "Gainde",
    "license": "LGPL-3",
    "depends": ["asset_management", "account_asset", "stock", "product", "maintenance"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/asset_inventory_scan_page.xml",
        "views/asset_management_views.xml",
        "views/asset_localisation_views.xml",
        "views/asset_dashboard_views.xml",
        "views/asset_management_picking_views.xml",
        "views/asset_transfer_entry_views.xml",
        "views/asset_transfer_order_views.xml",
        "views/asset_hide_complete.xml",
        "views/asset_inventory_views.xml",
        "views/asset_menu_reorganize.xml",
        "views/asset_inventory_session_views.xml",
        "views/asset_kanban_status_color.xml",
        "views/hr_employee_views.xml",
        "views/account_asset_views.xml",
        "views/product_template_views.xml",
        "views/stock_picking_views.xml",
        "views/asset_kanban_fix.xml",
        "wizard/asset_sortie_wizard_view.xml",
        "wizard/maintenance_request_wizard_view.xml",
        "report/asset_label_custom_report.xml",
        "report/asset_label_custom_templates.xml",
        "report/asset_inventory_report.xml",
        "report/asset_inventory_report_template.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "asset_management_override/static/src/css/asset_dashboard.css",
            "asset_management_override/static/src/js/asset_dashboard.js",
            "asset_management_override/static/src/xml/asset_dashboard.xml",
            "asset_management_override/static/src/js/inventory_barcode_scanner.js",
            "asset_management_override/static/src/xml/inventory_barcode_scanner.xml",
        ],
    },
    "installable": True,
    "application": False,
}
